# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- feature/*

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: packageAndPublish
  displayName: Package And Publish Buyingcatalogue
  # pool:
  #   name: GP IT Futures AKS Build Agents
  variables:
    - group: dev-acr-secrets
  steps:
  - task: UseGitVersion@5
    displayName: gitversion
    inputs:
      versionSpec: '5.x'
  - task: HelmInstaller@1
    displayName: 'install helm'
    inputs:
      helmVersionToInstall: 'latest'
  - bash: |      
      helm package \
          --version $(GitVersion.SemVer) \
          --app-version $(GitVersion.SemVer) \
          src/buyingcatalogue
    failOnStderr: true
    displayName: 'helm package'
  - bash: |      
      chartPackage=$(ls buyingcatalogue-*.tgz)
      echo "Chart Package $chartPackage"
      az --version
      az acr helm push --force \
          -n gpitfuturesdevacr \
          -u gpitfuturesdevacr \
          -p $(gpitfuturesdevacr-pass) \
          $chartPackage      
    failOnStderr: true
    name: helmPush
    displayName: 'az acr helm push'
  - script: echo "##vso[task.setvariable variable=semVer;isOutput=true]$(GitVersion.SemVer)"
    name: setVersionStep  
  - script: echo semver $(setVersionStep.semVer), MajorMinorPatch $(GitVersion.MajorMinorPatch), Reason $(Build.Reason), Branch $(Build.SourceBranch), BranchName $(Build.SourceBranchName), PRID $(System.PullRequest.PullRequestId), PRNumber $(System.PullRequest.PullRequestNumber)
    name: echovar
- job: deployToDev
  dependsOn: packageAndPublish
  variables:
    - group: dev-acr-secrets
    - name: semVer
      value: $[ dependencies.packageAndPublish.outputs['setVersionStep.semVer'] ]
  steps:
  - bash: | 
      namespace=`echo 'buyingcatalogue-$(Build.SourceBranchName)' | sed 's/[[:punct:]]/-/g'`      
      basePath="$namespace.dev.buyingcatalogue.digital.nhs.uk"
      baseUrl="https://$basePath"
      baseIdentityUrl="$baseUrl/identity"
      echo "##vso[task.setvariable variable=Namespace;isOutput=true]$namespace"
      echo "##vso[task.setvariable variable=BasePath;isOutput=true]$basePath"
      echo "##vso[task.setvariable variable=BaseUrl;isOutput=true]$baseUrl"
      echo "##vso[task.setvariable variable=BaseIdentityUrl;isOutput=true]$baseIdentityUrl"
    name: DeployVars
    # create namespace if it doesn't exist
  - task: Kubernetes@1
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: 'NHSAPP-BuyingCatalogue (Non-Prod)'
      azureResourceGroup: 'gpitfutures-dev-rg-aks'
      kubernetesCluster: 'gpitfutures-dev-aks'
      command: 'apply'
      useConfigurationFile: true
      configurationType: 'inline'
      inline: |
        {
          "apiVersion": "v1",
          "kind": "Namespace",
          "metadata": {
            "name": "$(DeployVars.Namespace)",
            "labels": {
              "name": "$(DeployVars.Namespace)"
            }
          }
        }
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'
    # deploy chart to namespace
  - task: HelmDeploy@0
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscription: 'NHSAPP-BuyingCatalogue (Non-Prod)'
      azureResourceGroup: 'gpitfutures-dev-rg-aks'
      kubernetesCluster: 'gpitfutures-dev-aks'
      namespace: '$(DeployVars.Namespace)'
      command: 'upgrade'
      chartType: 'Name'
      chartName: 'gpitfuturesdevacr/buyingcatalogue'
      releaseName: 'bc'
      overrideValues: 'appBaseUrl=$(DeployVars.BaseUrl),
      baseIsapiEnabledUrl=$(DeployVars.BaseIdentityUrl),
      isapi.clients[0].redirectUrls[0]=$(DeployVars.BaseUrl)/oauth/callback,
      isapi.clients[0].redirectUrls[1]=$(DeployVars.BaseUrl)/admin/oauth/callback,
      isapi.clients[0].redirectUrls[2]=$(DeployVars.BaseUrl)/order/oauth/callback,
      isapi.clients[0].postLogoutRedirectUrls[0]=$(DeployVars.BaseUrl)/signout-callback-oidc,
      isapi.clients[0].postLogoutRedirectUrls[1]=$(DeployVars.BaseUrl)/admin/signout-callback-oidc,
      isapi.clients[0].postLogoutRedirectUrls[2]=$(DeployVars.BaseUrl)/order/signout-callback-oidc,
      isapi.ingress.hosts[0].host=$(DeployVars.BasePath),
      email.ingress.hosts[0].host=$(DeployVars.BasePath),
      mp.ingress.hosts[0].host=$(DeployVars.BasePath),
      pb.ingress.hosts[0].host=$(DeployVars.BasePath),
      pb.baseUri=$(DeployVars.BaseUrl),
      admin.ingress.hosts[0].host=$(DeployVars.BasePath),
      of.ingress.hosts[0].host=$(DeployVars.BasePath),
      redis-commander.ingress.hosts[0].host=$(DeployVars.BasePath)'
      valueFile: 'environments/azure.yaml'
      arguments: '--debug '
# - job: runAcceptanceTests
#   dependsOn: packageAndPublish
#   variables:
#     - group: dev-acr-secrets
#   steps:
    # public browse
    # marketing pages
    # admin
    # order
    # identity
  