# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- feature/*

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: buyingcatalogue
  displayName: version and deploy buyingcatalogue
  pool:
    name: GP IT Futures AKS Build Agents
  variables:
    - group: dev-acr-secrets
  steps:
  - task: UseGitVersion@5
    displayName: gitversion
    inputs:
      versionSpec: '5.x'
  - script: echo semver $(GitVersion.SemVer), MajorMinorPatch $(GitVersion.MajorMinorPatch), Reason $(Build.Reason), Branch $(Build.SourceBranch), BranchName $(Build.SourceBranchName), PRID $(System.PullRequest.PullRequestId), PRNumber $(System.PullRequest.PullRequestNumber)
    name: echovar
  - task: HelmInstaller@1
    displayName: 'install helm'
    inputs:
      helmVersionToInstall: 'latest'
  - bash: |      
      helm package \
          --version $(GitVersion.SemVer) \
          --app-version $(GitVersion.SemVer) \
          src/buyingcatalogue
    failOnStderr: true
    displayName: 'helm package'
  - bash: |      
      chartPackage=$(ls buyingcatalogue-*.tgz)
      echo "Chart Package $chartPackage"
      az --version
      az acr helm push --force \
          -n gpitfuturesdevacr \
          -u gpitfuturesdevacr \
          -p $(gpitfuturesdevacr-pass) \
          $chartPackage      
    failOnStderr: true
    name: helmPush
    displayName: 'az acr helm push'