trigger: none
pr: none

resources: 
  pipelines:
  - pipeline: azure-pipelines
    source: nhs-digital-gp-it-futures.platform-helm
    trigger:
      enabled: true
      branches:
        include:
          - master
          - feature/*

stages:
- stage: development
  displayName: development
  jobs:
  - deployment: development
    variables:  
      - group: dev-acr-secrets          
      - name: namespace
        value: buyingcatalogue-development
      - name: basePath
        value: $(namespace)-dev.buyingcatalogue.digital.nhs.uk      
      - name: baseUrl
        value: https://$(basePath)
      - name: baseIdentityUrl
        value: $(baseUrl)/identity
    displayName: deploy helm chart into AKS
    pool:
      vmImage: 'ubuntu-latest'
    environment: development-$(projectName)
    strategy:
      runOnce:
        deploy:
          steps: 
            - checkout: none
            - task: HelmInstaller@1
              displayName: 'install helm'
              inputs:
                helmVersionToInstall: 'latest'
            - task: DownloadPipelineArtifact@2
              inputs:
                artifact: build-artifact
            - bash: | 
                echo "pipeline.workspace=$(pipeline.workspace)"
                env | sort
                ls $(pipeline.workspace)
                helmChartVersion=$(jq .helmChartVersion $(pipeline.workspace)/azure-pipelines/build-artifact/variables.json -r)
                echo "helmChartVersion=$helmChartVersion"
                echo "##vso[task.setvariable variable=Version;isOutput=true]$helmChartVersion"
              failOnStderr: true
              displayName: 'helm repo add'
              name: Version
              # create namespace if it doesn't exist
            - task: Kubernetes@1
              inputs:
                connectionType: 'Azure Resource Manager'
                azureSubscriptionEndpoint: 'NHSAPP-BuyingCatalogue (Non-Prod)'
                azureResourceGroup: 'gpitfutures-dev-rg-aks'
                kubernetesCluster: 'gpitfutures-dev-aks'
                command: 'apply'
                useConfigurationFile: true
                configurationType: 'inline'
                inline: |
                  {
                    "apiVersion": "v1",
                    "kind": "Namespace",
                    "metadata": {
                      "name": "$(namespace)",
                      "labels": {
                        "name": "$(namespace)"
                      }
                    }
                  }
                secretType: 'dockerRegistry'
                containerRegistryType: 'Azure Container Registry'
            - bash: |      
                helm repo add \
                gpitfuturesdevacr \
                https://gpitfuturesdevacr.azurecr.io/helm/v1/repo \
                --username gpitfuturesdevacr \
                --password $(gpitfuturesdevacr-pass)
              failOnStderr: true
              displayName: 'helm repo add'
              # deploy chart to namespace
            - task: HelmDeploy@0
              inputs:
                connectionType: 'Azure Resource Manager'
                azureSubscription: 'NHSAPP-BuyingCatalogue (Non-Prod)'
                azureResourceGroup: 'gpitfutures-dev-rg-aks'
                kubernetesCluster: 'gpitfutures-dev-aks'
                namespace: '$(namespace)'
                command: 'upgrade'
                chartType: 'Name'
                chartName: 'gpitfuturesdevacr/buyingcatalogue'
                releaseName: 'bc'
                overrideValues:
                valueFile: 'environments/azure.yaml'
                arguments: >   
                  --version $(Version.Version)
                  --timeout 10m0s
                  --set dbPassword=$(gpitfuturesdevdbpassword)-$(namespace)
                  --set clientSecret=$(gpitfuturesdevclientsecret)-$(namespace)
                  --set appBaseUrl=$(baseUrl)
                  --set baseIsapiEnabledUrl=$(DeployVars.BaseIdentityUrl)
                  --set isapi.clients[0].redirectUrls[0]=$(baseUrl)/oauth/callback
                  --set isapi.clients[0].redirectUrls[1]=$(baseUrl)/admin/oauth/callback
                  --set isapi.clients[0].redirectUrls[2]=$(baseUrl)/order/oauth/callback
                  --set isapi.clients[0].postLogoutRedirectUrls[0]=$(baseUrl)/signout-callback-oidc
                  --set isapi.clients[0].postLogoutRedirectUrls[1]=$(baseUrl)/admin/signout-callback-oidc
                  --set isapi.clients[0].postLogoutRedirectUrls[2]=$(baseUrl)/order/signout-callback-oidc
                  --set isapi.ingress.hosts[0].host=$(basePath)
                  --set isapi.hostAliases[0].hostnames[0]=$(basePath)
                  --set oapi.hostAliases[0].hostnames[0]=$(basePath)
                  --set ordapi.hostAliases[0].hostnames[0]=$(basePath)
                  --set email.ingress.hosts[0].host=$(basePath)
                  --set mp.ingress.hosts[0].host=$(basePath)
                  --set pb.ingress.hosts[0].host=$(basePath)
                  --set pb.baseUri=$(baseUrl)
                  --set pb.hostAliases[0].hostnames[0]=$(basePath)
                  --set admin.ingress.hosts[0].host=$(basePath)
                  --set admin.hostAliases[0].hostnames[0]=$(basePath)
                  --set of.ingress.hosts[0].host=$(basePath)
                  --set of.hostAliases[0].hostnames[0]=$(basePath)
                  --set redis-commander.ingress.hosts[0].host=$(basePath)
            
